spring:
  cloud:
    stream:
      kafka:
        binder:
          brokers: localhost:9092
      bindings:
        output:
          destination: testTopic
          content-type: application/json
        input:
          destination: testTopic
          content-type: application/json
          group: testGroup
          resetOffsets: true

server:
  port: 8080

management:
  security:
    enabled: false
